### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by artemnovichkov** [pedrommcarrasco/Brooklyn#15]
#### General troubleshooting

Before logging an issue please verify that:
- [x] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [x] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Air (13-inch, Early 2015)
- [x] macOS version: 10.13.6 (17G65)

#### Description of issue

I see an error in Screen Saver Settings:
```
You cannot use the SavingYourScreen screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver.
```

**Comment by pedrommcarrasco** [comment]
Hey @artemnovichkov 👋 
Mac is a bit weird when it comes to screensavers written in Swift, delete it, **close settings** (👈 this is very important) and try again.
If this doesn't work, it'll be hard to solve since I cannot reproduce it. If you want to give it a try feel free to fork it & please open a pull request if you find a way to solve it.

Please report back

**Comment by artemnovichkov** [comment]
Hm, it works now. In my opinion, you should note this case in Installation section.

**Comment by pedrommcarrasco** [comment]
It is mentioned in the installation section but yeah, maybe we should add a troubleshooting section mentioning this.
Free free to open a PR adding this @artemnovichkov
