### ISSUE TITLE
Configure the duration of each screen

### ISSUE THREAD

**Issue by noniagriconomie** [pedrommcarrasco/Brooklyn#38]
Hi, first of all thank you for your screen saver, it is much appreciated :)

Here is one feature request, event if I do not know the feasability
Some screens are very short, i would like to know if it can be configurable to loop them

###  Describe the solution you'd like
In the configuration menu, maybe add an input which takes an integer as second
The related screen will then loop this amount of second

Feel free to close this issue if it is not doable :)

Cheers!

**Comment by pedrommcarrasco** [comment]
Hello @noniagriconomie and welcome here! Glad you enjoyed 😄 
Configuring seconds isn't very doable because most of them have different lengths. That's why that option is called "number of loops" -  it ignores how long the animation is, it just loops in N times.

What could be an animation would be selecting how much loops each animation does individually but I'm afraid that would be would make the panel look like a mess. I'm closing this for now, but maybe we can revisit this in the future.
